language: ruby
dist: bionic
cache: bundler
rvm:
  - 2.6
env:
  - GNUPGHOME=/tmp/fauna_fake_gpg_home RAILS_ENV=test
script:
  - RAILS_ENV=test bundle exec rake --trace spec
before_script:
  - psql -c 'create database fauna_development;' -U postgres
  - psql -c 'create database fauna_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - mkdir $GNUPGHOME
  - gpg -K
  - gpg --gen-key --batch spec/support/test_gpg_key_generation.batch
  - bin/setup -u travis -e travis@example.com -n travis -p foobarbaz
after_script:
  - cat log/test.log
addons:
  apt:
    packages:
      - chromium-chromedriver
services:
  - postgresql
