language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
script:
  - RAILS_ENV=test bundle exec rake --trace initial_setup spec
before_script:
  - cp config/database.yml.travis config/database.yml